# Generated by Django 5.0 on 2023-12-09 07:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extension', models.CharField(choices=[('pdf', 'Portable Document'), ('xls', 'Excel Worksheet'), ('xlsx', 'Excel Spreadsheet'), ('doc', 'Word Document'), ('docx', 'Word Text Document'), ('ppt', 'Powerpoint Presentation'), ('pptx', 'Powerpoint Presentation Document'), ('txt', 'Plain Text'), ('md', 'Markdown Documentation')], max_length=5)),
            ],
            options={
                'db_table': 'tb_file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('email', models.CharField(max_length=256)),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='RSAKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
            options={
                'db_table': 'tb_rsa_keypair',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('action', models.CharField(choices=[('encrypt', 'File Encrypted'), ('decrypt', 'File Decrypted'), ('delete', 'File Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
            options={
                'db_table': 'tb_log',
            },
        ),
    ]
