# Generated by Django 5.0 on 2023-12-15 03:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decryption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
            options={
                'db_table': 'tb_decryption',
            },
        ),
    ]
