# Generated by Django 5.0.6 on 2024-06-16 17:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('format_name', models.CharField(max_length=50)),
                ('fields', models.JSONField()),
            ],
            options={
                'db_table': 'tb_format_data',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('email', models.CharField(max_length=256)),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extension', models.CharField(choices=[('pdf', 'Portable Document'), ('xls', 'Excel Worksheet'), ('xlsx', 'Excel Spreadsheet'), ('doc', 'Word Document'), ('docx', 'Word Text Document'), ('ppt', 'Powerpoint Presentation'), ('pptx', 'Powerpoint Presentation Document'), ('txt', 'Plain Text'), ('md', 'Markdown Documentation')], max_length=5)),
                ('aes_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.formatdata')),
            ],
            options={
                'db_table': 'tb_file',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('data', models.JSONField()),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.formatdata')),
            ],
            options={
                'db_table': 'tb_data',
            },
        ),
        migrations.CreateModel(
            name='RSAKeyPair',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.file')),
            ],
            options={
                'db_table': 'tb_rsa_keypair',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 11, 11))),
                ('action', models.CharField(choices=[('encrypt', 'File Encrypted'), ('decrypt', 'File Decrypted'), ('delete', 'File Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'tb_log',
            },
        ),
    ]
