# Generated by Django 5.0.6 on 2024-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='identity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
