# Generated by Django 5.0.6 on 2024-06-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='vector',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
